import { MantineProvider } from "@mantine/core";
import "./globals.css";
import '@mantine/core/styles.css';
export const metadata = {
  title: "Education India",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MantineProvider defaultColorScheme="light">
     { children}
      </MantineProvider>
      </body>
    </html>
  );
}
