
import { CssBaseline } from '@mui/material';
import "./globals.css";
import { createTheme, MantineProvider } from '@mantine/core'
export const metadata = {
  title: "Education India",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      < CssBaseline />
      <body>{
       <MantineProvider theme={"dark"}>{children}</MantineProvider>
       }</body>
    </html>
  );
}
